# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Build and deploy book

jobs: 
  build_to_ghp:
     runs-on: ubuntu-latest
     steps: 
       - name: Setup Git Identity
         run: |
           git config --global user.email "siqi.zhang@bayer.com"
           git config --global user.name "Siqi Z. Bot"
           
       - name: Checkout Repo
         uses: actions/checkout@v3
        
       - name: Setup R
         uses: r-lib/actions/setup-r@v2
         with:
           use-public-rspm: true
           r-version: "4.0.5"
          
       - name: Install Pandoc
         if: ${{ ! github.event.inputs.ghpages }}
         uses: r-lib/actions/setup-pandoc@v2
         with:
           pandoc-version: '2.17.1.1'
           
       - name: Install TinyTeX
         uses: r-lib/actions/setup-tinytex@v2
         env:
           # install full prebuilt version
           TINYTEX_INSTALLER: TinyTeX
         
       - name: Install nlopt
         run: sudo apt-get install libnlopt-dev

       - name: Build & push
         run: |
           cd ${{ github.workspace }}

           R -e "renv::restore()"
           R -e 'bookdown::render_book(output_dir = "docs")'
           
#           git checkout -b gh-pages
#           touch docs/.nojekyll
#           git add .
#           git commit -m "build book" 
#           git push -uf origin HEAD
           
       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@v4
         with:
           branch: gh-pages
           folder: docs
        
  build_to_intranet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with: 
           ref: main
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
           use-public-rspm: true
           r-version: "4.0.5"
          
      - name: Install Pandoc
        run: brew install pandoc
      - name: Install nlopt
        run: sudo apt-get install libnlopt-dev
        
      - name: Build & push
        run: |
           R -e "renv::restore()"
           R -e 'bookdown::render_book(output_dir = "site")'

      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: site/

  deploy_to_intranet:
    name: "Publish Docs"
    needs: build_to_intranet
    
    # See the full reference for available parameters https://docs.int.bayer.com/ref/
    uses: bayer-int/actions-workflows/.github/workflows/publish-docs.yml@main
    with:
      artifact: site
      dir:      site
      preview:  ${{ github.ref != 'refs/heads/main' && github.run_id || '' }}
      # namespace:  'example' # add a custom path your documentation will be available on
