on:
  push:
    branches: [main]

name: Build and deploy book

jobs: 

  build_bookdown:
    name: "Build Bookdown Site"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with: 
           ref: ${{github.ref}}
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
           use-public-rspm: true
           r-version: "4.0.5"
          
      - name: Install System Dependencies
        run: |
          brew install pandoc
          sudo apt-get install libnlopt-dev
        
      - name: Render Book
        run: |
           R -e "renv::restore()"
           R -e 'bookdown::render_book(output_dir = "site")'
           touch site/.nojekyll 

      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: site/

  publish_to_ghp: 
    name: "Publish to GitHub Pages"
    if: ${{github.ref}} == "main"
    runs-on: ubuntu-latest
    needs: build_bookdown
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with: 
        ref: ${{github.ref}}
    - uses: actions/download-artifact@v3
      with: 
        name: site
        path: site/
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: site

  publish_to_intranet:
    name: "Publish to DevDocs on Intranet"
    needs: build_bookdown
    
    # See the full reference for available parameters https://docs.int.bayer.com/ref/
    uses: bayer-int/actions-workflows/.github/workflows/publish-docs.yml@main
    with:
      artifact: site
      dir:      site
      preview:  ${{ github.ref != 'refs/heads/main' && github.run_id || '' }}
      # namespace:  'example' # add a custom path your documentation will be available on
