# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

name: build_bookdown

jobs: 
  build_bookdown:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/checkout@v2
         with: 
           repository: ${{ github.repository }}
           ref: dev
           token: ${{ secrets.MY_GITHUB_TOKEN }}
        
       - uses: r-lib/actions/setup-r@v1
         with:
           use-public-rspm: true
           r-version: "4.0.0"
          
     #  - uses: r-lib/actions/setup-r-dependencies@v1
      
       - name: scratch
         run: |
            cd ${{ github.workspace }}
            pwd
            ls
            
       - uses: actions/checkout@v3
         with:
            ref: dev
            
       - name: install pandoc
         run: brew install pandoc

       - name: build
         run: |
           cd ${{ github.workspace }}
           R -e "renv::restore()"
           R -e 'install.packages("bookdown")'
           R -e "bookdown::render_book()"
           git add . 
           git commit -m "render book" 
           git status
           # git push origin
        
